[package]
name = "xlog-decoder"
version = "1.0.0"
description = "A desktop application for decode mars-xlog"
authors = ["porum"]
license = "Apache-2.0"
repository = "https://github.com/porum/xlog-decoder"
edition = "2021"
rust-version = "1.77"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
custom-protocol = ["tauri/custom-protocol"]
